config/routes.rb
Rails.application.routes.draw do
  resources :matric_school_reports, only: [:index, :create, :show]
  root to: "matric_school_reports#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/matric_school_report.rb
class MatricSchoolReport < ApplicationRecord
  validates :school, uniqueness: { scope: :year }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  skip_before_action :verify_authenticity_token
end

app/controllers/matric_school_reports_controller.rb
class MatricSchoolReportsController < ApplicationController
  http_basic_authenticate_with name: "you_shall_not", password: "pass", except: :index


  def index
    @matric_school_reports = MatricSchoolReport.all
    @total_schools = @matric_school_reports.pluck(:school).uniq.count
    @yearly_summaries = @matric_school_reports.group_by{ |r| r.year }.map do |year, results|
      { year: year,
        wrote_total: results.map(&:wrote).sum,
        pass_total: results.map(&:passed).sum,
        pass_average: (results.map(&:passed).sum.to_f * 100/results.map(&:wrote).sum.to_f).to_i
      }
    end

    @histoplot_2014 = @matric_school_reports.where(year: 2016).where("wrote > 0").group_by{ |r| (r.passed.to_f * 100/r.wrote.to_f).to_i}.map{ |percentage, results| [percentage, results.count]}.sort
    @histoplot_2015 = @matric_school_reports.where(year: 2015).where("wrote > 0").group_by{ |r| (r.passed.to_f * 100/r.wrote.to_f).to_i}.map{ |percentage, results| [percentage, results.count]}.sort
    @histoplot_2016 = @matric_school_reports.where(year: 2014).where("wrote > 0").group_by{ |r| (r.passed.to_f * 100/r.wrote.to_f).to_i}.map{ |percentage, results| [percentage, results.count]}.sort

    respond_to do |format|
      format.html
      format.json { @matric_school_reports }
    end
  end

  def show
    matric_school_reports = MatricSchoolReport.find(matric_school_report_id)
    render json: matric_school_reports
  end


  def create
    matric_school_report = MatricSchoolReport.new(matric_school_report_params)

    if matric_school_report.save
      head :ok
    else
      render json: matric_school_report.errors, status: :unprocessable_entity
    end
  end


  private
    def matric_school_report_params
      params.permit(:school, :year, :wrote, :passed, :id)
    end

    def matric_school_report_id
      matric_school_report_params["id"].to_i
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matric_school_reports_helper.rb
module MatricSchoolReportsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZyelabsTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/matric_school_reports/_form.html.erb
<%= form_with(model: matric_school_report, local: true) do |form| %>
  <% if matric_school_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(matric_school_report.errors.count, "error") %> prohibited this matric_school_report from being saved:</h2>

      <ul>
      <% matric_school_report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/matric_school_reports/edit.html.erb
<h1>Editing Matric School Report</h1>

<%= render 'form', matric_school_report: @matric_school_report %>

<%= link_to 'Show', @matric_school_report %> |
<%= link_to 'Back', matric_school_reports_path %>

app/views/matric_school_reports/index.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<div class="container">
  <h1>Matric School Reports</h1>
  <div class="well">Total schools analyzed: <%= @total_schools%></div>

  <h3>Matric school summary:</h3>
  <table class="table table-striped">
      <tr>
        <th>Year</th>
        <th>Wrote</th>
        <th>Passed</th>
        <th>Average</th>
      </tr>
      <% @yearly_summaries.each do |yearly_summary| %>
        <tr>
          <td><%= yearly_summary[:year] %></td>
          <td><%= yearly_summary[:wrote_total] %></td>
          <td><%= yearly_summary[:pass_total] %></td>
          <td><%= yearly_summary[:pass_average] %></td>
        </tr>
      <% end %>
  </table>

  <br>
  <h3>Summary:</h3>

  <%= column_chart [{name: '2014', data: @histoplot_2014}, {name: '2015', data: @histoplot_2015}, {name: '2016', data: @histoplot_2016}] %>

</div>

app/views/matric_school_reports/new.html.erb
<h1>New Matric School Report</h1>

<%= render 'form', matric_school_report: @matric_school_report %>

<%= link_to 'Back', matric_school_reports_path %>

app/views/matric_school_reports/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_matric_school_report_path(@matric_school_report) %> |
<%= link_to 'Back', matric_school_reports_path %>